### ISSUE TITLE
Type error in declaration files

### ISSUE THREAD

**Issue by Methuselah96** [pmndrs/drei#2013]
- `three` version: N/A
- `@react-three/fiber` version: N/A
- `@react-three/drei` version: 9.108.1
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

### Problem description:

Running type-checking with `skipLibCheck` set to `false` reports the following error:

```
Error: ./node_modules/@react-three/drei/core/Bvh.d.ts(1,22): error TS6053: File './node_modules/@react-three/custom.d.ts' not found.
```

The problem can be seen by inspecting `Bvh.d.ts`, which has a reference to `custom.d.ts` which is not within the published package:

![image](https://github.com/pmndrs/drei/assets/693755/6438680c-fc13-401e-b07c-d03764f5c65e)

This is likely introduced in https://github.com/pmndrs/drei/pull/1999, with the TypeScript version upgrade.

### Relevant code:

N/A

### Suggested solution:

Remove custom.d.ts: https://github.com/pmndrs/drei/pull/2014
