### ISSUE TITLE
CJS build in v9.116.0 breaks Next.js projects (TypeError: a is not a function)

### ISSUE THREAD

**Issue by rossyman** [pmndrs/drei#2198]
- `three` version: 0.170.0
- `@react-three/fiber` version: 8.17.10
- `@react-three/drei` version: 9.116.0
- `node` version: 20.10.0
- `npm` (or `yarn`) version: 10.2.3 (Also on bun: 1.1.34) 

### Problem description:

v9.116.0 CJS build breaks Next.js projects. Previously resolved in this discussion: https://github.com/pmndrs/drei/issues/1544

```
unhandledRejection: TypeError: a is not a function
    at Object.<anonymous> (/node_modules/@react-three/drei/index.cjs.js:1:8647)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
```

### Relevant code:

Seems to be zustand related code.

```
@react-three/drei/index.cjs.js:1:8647
```

#### v9.115.0 build (Working):
<img width="944" alt="Screenshot 2024-11-13 at 12 15 01" src="https://github.com/user-attachments/assets/e725a93b-5c9e-42cf-bca6-074e4b5b0168">

#### v9.116.0 build (Broken):
<img width="965" alt="Screenshot 2024-11-13 at 12 16 03" src="https://github.com/user-attachments/assets/97b9508f-0b76-479d-bd85-f4080b6cfde8">

### Suggested solution:

Downgrade to v9.115.0

**Comment by Sonnpm197** [comment]
I tried to render in vitest with a component for drei

`import React from "react";
import {OrbitControls} from "@react-three/drei";
import {Canvas} from "@react-three/fiber";

const FirstTest = () => {
    return (
        <Canvas>
            <OrbitControls />
        </Canvas>
    )
}
export default FirstTest`

`import {render, screen} from '@testing-library/react'
import FirstTest from './FirstTest.jsx'

test('loads and displays greeting', () => {
    render(<FirstTest />)
})`

Also face the same issue, downgrade to 9.115.0 also doesn't work
Any recommendations?

**Comment by abernier** [comment]
I think it is the same issue we had previously when upgraded to rollup 3: https://github.com/pmndrs/drei/pull/1570

@CodyJasonBennett can we find a fix and keep rollup4?

**Comment by CodyJasonBennett** [comment]
We need to revert the upgrade and ensure we have e2e tests that consume CJS before we retry. If we opt out of SSR in Next, then that skips CJS, for instance.

**Comment by abernier** [comment]
I'm reverting the https://github.com/pmndrs/drei/commit/63c331fbac83bcf363986faec7a3abd2b1c44ecb commit in this PR https://github.com/pmndrs/drei/pull/2200

**Comment by abernier** [comment]
@CodyJasonBennett I will try adding a SSR e2e test

**Comment by abernier** [comment]
@CodyJasonBennett there is now a cjs e2e test that makes the previous rollup4 commit fail https://github.com/pmndrs/drei/actions/runs/11877820543/job/33097749021?pr=2201#step:8:798
