### ISSUE TITLE
SoftShadows broken with three.js r182 (unpackRGBAToDepth removed)

### ISSUE THREAD

**Issue by xhorntail** [pmndrs/drei#2583]
- `three` version: 0.182.0 (works on 0.181.0)
- `@react-three/fiber` version: 9.4.2
- `@react-three/drei` version: 10.7.7
- `node` version: 24.10.0
- `npm` (or `yarn`) version: npm 11.6.4

### Problem description:

`<SoftShadows />` throws shader compilation errors with three.js r182. 

three.js r182 modernized shadow mapping (PRs #32181, #32303, #32407, #32443), switching from RGBA-packed depth to native depth textures. The `unpackRGBAToDepth()` function was removed from the shader chunks as a result.

drei's PCSS shader still calls `unpackRGBAToDepth()` to sample shadow maps:

```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false
Material Type: MeshStandardMaterial

FRAGMENT
ERROR: 0:1304: 'unpackRGBAToDepth' : no matching overloaded function found
```

### Relevant code:

```jsx
import { SoftShadows } from '@react-three/drei'

<Canvas shadows>
  <SoftShadows />
  {/* any scene with shadows */}
</Canvas>
```

The problematic code is in [`src/core/softShadows.tsx`](https://github.com/pmndrs/drei/blob/4a367bf6c3f3b1ff5b1adab76e4430c6c1f5e81e/src/core/softShadows.tsx#L86) , which injects:
```glsl
depth = unpackRGBAToDepth( texture2D( shadowMap, uv + offset));
```

### Suggested solution:

Update the PCSS shader to sample depth textures directly:
```glsl
depth = texture2D(shadowMap, uv + offset).r;
```

**Comment by DennisSmolek** [comment]
Soft Shadows is REALLY hard... I have fixed this for legacy to match 182 but it will be a bit before its done in webgpu.

To track webgpu see #2664

**Comment by iangilman** [comment]
@DennisSmolek Bravo! If you wouldn't mind, I'd love it if you could point me toward the fix? I'm not finding it looking through the commits or the PRs here...

**Comment by mracette** [comment]
Has this been released?
