### ISSUE TITLE
OrbitControls broken since 1.4.0

### ISSUE THREAD

**Issue by ptsteadman** [pmndrs/drei#132]
See CodeSandbox: https://codesandbox.io/s/r3f-contact-shadow-forked-hc4s7?file=/src/index.js

The controls work fine up to version 1.3.2, but after 1.4.0 there's an error in the Three.JS OrbitControls update function and the controls fail to initialize:
```
TypeError
Cannot read property 'x' of undefined
Vector3.copy
https://hc4s7.csb.app/node_modules/three/build/three.module.js:1:111602
OrbitControls.update
https://hc4s7.csb.app/node_modules/three/examples/jsm/controls/OrbitControls.js:95:14
```

Perhaps the API has changed somehow?

**Comment by ChrisDesigns** [comment]
All controls but TransformControls seem to return an error.

DeviceOrientationControls returns:
Cannot read property 'setFromEuler' of undefined

FlyControls returns:
scope.object.translateX is not a function

Both FlyControls and MapControls return the error mentioned in your issue.

**Comment by pr1ntr** [comment]
yeah i just spent my morning trying to figure out why none of this works...

**Comment by gsimone** [comment]
@ptsteadman the sandbox works with latest drei (1.5.6) & latest react-three-fiber (4.2.21)

**Comment by ptsteadman** [comment]
Thanks @gsimone ! I checked and the other controls seem to be working as well. I'll close this issue.
